version: '3.3'

services:
  epic_ml_visualizer:
    build: .
    image: duffy356/dsc_final_project_epic_ml_visualizer:latest
    ports:
      - 39005:${STREAMLIT_SERVER_PORT:-80}
    environment:
      - STREAMLIT_SERVER_PORT=${STREAMLIT_SERVER_PORT:-80}
